
homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
group: !include groups.yaml
light: !include lights.yaml
script: !include scripts.yaml
scene: !include scenes.yaml