# FRONT PORCH
- platform: switch
  entity_id: switch.fan_and_light_switch_front_porch

# FRONT OFFICE
- platform: switch
  entity_id: switch.fan_and_light_switch_front_office

# KITCHEN
- platform: switch
  entity_id: switch.pendant_light_switch_kitchen

# HALLWAY
- platform: switch
  entity_id: switch.overhead_lights_hallway
- platform: switch
  entity_id: switch.overhead_light_hallway_coat_closet
- platform: switch
  entity_id: switch.light_deck

# POWDER ROOM
- platform: switch
  entity_id: switch.vanity_light_powder_room
- platform: switch
  entity_id: switch.fan_and_overhead_light_powder_room

# MASTER BEDROOM
- platform: switch
  entity_id: switch.overhead_lights_scene_controller_master_bedroom
- platform: switch
  entity_id: switch.fan_and_light_master_bedroom
- platform: switch
  entity_id: switch.bed_lamp_tammy_master_bedroom
- platform: switch
  entity_id: switch.bed_lamp_jim_master_bedroom  

# BACK OFFICE
- platform: switch
  entity_id: switch.fan_and_light_switch_back_office
- platform: switch
  entity_id: switch.closet_light_back_office

# MASTER BATHROOM
- platform: switch
  entity_id: switch.exhaust_fan_master_bathroom
- platform: switch
  entity_id: switch.left_vanity_lights_master_bathroom
- platform: switch
  entity_id: switch.right_vanity_lights_master_bathroom

  #- platform: switch
#  entity_id: switch.overhead_lights_mbrtest_fan