# FRONT PORCH
- platform: switch
  name: Fans and Lights - Front Porch
  entity_id: switch.fan_and_light_switch_front_porch

# FRONT OFFICE
- platform: switch
  name: Fan and Light - Front Office
  entity_id: switch.fan_and_light_switch_front_office