- platform: hydrawise

- platform: average
  name: Average House Temperature
  entities:
    - sensor.main_floor_temperature
    - sensor.bedroom_temperature

- platform: template
  sensors:
    blind_state_sensor_front_officed_front:
      value_template: >
        {% if is_state('input_number.front_office_cover_front', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    blind_state_sensor_front_office_side:
      value_template: >
        {% if is_state('input_number.front_office_cover_side', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    blind_state_sensor_living_room_side_left:
      value_template: >
        {% if is_state('input_number.living_room_cover_side_left', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    blind_state_sensor_living_room_side_center:
      value_template: >
        {% if is_state('input_number.living_room_cover_side_center', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    blind_state_sensor_living_room_side_right:
      value_template: >
        {% if is_state('input_number.living_room_cover_side_right', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    blind_state_sensor_living_room_front:
      value_template: >
        {% if is_state('input_number.living_room_cover_front', '0.0') %}
          Open
        {% else %}
          Closed
        {% endif %}

- platform: template
  sensors:
    lycklig_range:
      value_template: "{{ states('sensor.lycklig_range_sensor') | int }}"

- platform: template
  sensors:
    lycklig_odometer:
      value_template: "{{ '{0:_.0f}'.format(states.sensor.lycklig_mileage_sensor.state | int).replace('_', ',')}}"

- platform: google_geocode
  name: Jim's Ipad
  origin: device_tracker.jamess_ipad_2
  options: 'street_number, street, city, state'
  api_key: !secret google_maps_api_key

- platform: google_geocode
  name: EPace
  origin: device_tracker.jaguar_epace
  options: 'street_number, street, city, state'
  api_key: !secret google_maps_api_key

- platform: mqtt_room
  device_id: "irk:7ea07914324d1c2af3c65006f08a40f6"
  name: 'Beacon - Jims Iphone'
  state_topic: 'espresense/rooms'
  timeout: 30
  away_timeout: 120

- platform: mqtt_room
  device_id: "irk:014364bfbd1ed7ec853e0b28c2fed326"
  name: 'Beacon - Jims Apple Watch'
  state_topic: 'espresense/rooms'
  timeout: 5
  away_timeout: 120

# - platform: mqtt_room
#   device_id: "apple:1005:9-8"
#   name: 'Beacon - Jims Work Iphone'
#   state_topic: 'espresense/rooms'
#   timeout: 5
#   away_timeout: 120

- platform: mqtt_room
  device_id: "apple:1007:11-12"
  name: 'Beacon - Tammys Iphone'
  state_topic: 'espresense/rooms'
  timeout: 5
  away_timeout: 120

- platform: mqtt_room
  device_id: "irk:3a4dfee31144dca22a278fcfad35a2d2"
  name: 'Beacon - Tammys Apple Watch'
  state_topic: 'espresense/rooms'
  timeout: 5
  away_timeout: 120