- platform: hydrawise

- platform: template
  switches:
    skylight:
      value_template: "{{ is_state('lock.jag_doors', 'unlocked') }}"
        turn_on:
          service: jlrincontrol.lock_vehicle
          target:
            entity_id: sensor.jag_info
          data:
            pin: !secret jag_pin
        turn_off:
          service: jlrincontrol.unlock_vehicle
          target:
            entity_id: sensor.jag_info