sensor:
  - name: "Jag Distance to Service"
    icon: "mdi:wrench"
    state: "{{ state_attr('sensor.jag_all_info', 'core status').extKilometersToService | int}}"
    unit_of_measurement: km
    state_class: measurement
    availability: "{{ state_attr('sensor.jag_all_info', 'core status').extKilometersToService | int('unavailable') is number}}"